# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: oc-cmd@3
  inputs:
    connectionType: 'OpenShift Connection Service'
    version: '4.2'
    cmd: 'oc project HelloGrensinfo'

- task: oc-cmd@3
  inputs:
    connectionType: 'OpenShift Connection Service'
    version: '4.2'
    cmd: 'oc new-app https://github.com/huizecavia/HelloGrensinfo.git'

- task: oc-cmd@3
  inputs:
    connectionType: 'OpenShift Connection Service'
    version: '4.2'
    cmd: 'oc expose svc HelloGrensinfo-app'

- task: oc-cmd@3
  inputs:
    connectionType: 'OpenShift Connection Service'
    version: '4.2'
    cmd: 'oc start-build HelloGrensinfo --follow'

- task: oc-cmd@3
  inputs:
    connectionType: 'OpenShift Connection Service'
    version: '4.2'
    cmd: 'oc status'
